version: '2'

services:
    python:
        privileged: true
        volumes:
            - .:/var/project/dice
            - /sys
            - /lib/modules
        devices:
            - /dev/mem
            - /dev/gpiomem
            - /dev/i2c-1
